layout_spectrum: 0.15928485174663365
typography_spectrum: 0.9240911486558616
color:
  brandStrength: 0.3418780155479908
  lightness: 0.22747016628272831
  saturation: 0.24777828226797283
  rhythmicContrast: 0.395655810367316
  brandColors:
    - '#10222B'
    - '#95AB63'
    - '#BDD684'
    - '#E2F0D6'
    - '#F6FFE0'
name: www.corarecords.com
